### ISSUE TITLE
xauth: file list does not exist

### ISSUE THREAD

**Issue by glongo** [Bumblebee-Project/bumblebee-gentoo#21]
Hello,
i'm trying to start bumblebee server, but i've got this error:

xauth: file list does not exist

Any ideas?

Thanks,
Regards.

**Comment by williamspatrick** [comment]
The xauth file on my system shows up in /run instead of /var:
 6987 tty7     Ssl+   3:08 /usr/bin/Xorg :0 -background none -noreset -verbose -auth /run/gdm/auth-for-gdm-eZiJQP/database -nolisten tcp vt7

I changed the /var to /run in this:
    - XAUTHORITY="$(ps wwax -C X,Xorg -o args= --sort=-stime | grep -m 1 -o '\B[-]auth\s*/var\S*' | cut -d ' ' -f 2)"
    + XAUTHORITY="$(ps wwax -C X,Xorg -o args= --sort=-stime | grep -m 1 -o '\B[-]auth\s*/run\S*' | cut -d ' ' -f 2)"
