### ISSUE TITLE
Error on unloading nvidia module

### ISSUE THREAD

**Issue by DasLeo** [Bumblebee-Project/bumblebee-gentoo#22]
Could you please add this patch to repository, otherwise the nvidia module unloading after closing optirun timed out.
http://pastebin.com/TxRjJraP

**Comment by ex0hunt** [comment]
A new unloading error with x11-drivers/nvidia-drivers-358.16-r1(+kms). Patch there in https://github.com/Bumblebee-Project/Bumblebee/commit/1ada79fe5916961fc4e4917f8c63bb184908d986  Could you add support "develop" branch of bumblebee-project in ebuild or only this commit as patch?
